### ISSUE TITLE
AMValueError: invalid literal for int() with base 10: 'tcp://clamav:3310'

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/inbox#107]
A exceção abaixo ocorre ao iniciar o _celeryworker_:

```
2/8/2017 11:26:01 AM[2017-02-08 13:26:01,144: ERROR/MainProcess] Signal handler <bound method DjangoWorkerFixup.on_worker_ready of <celery.fixups.django.DjangoWorkerFixup object at 0x7ffa37e45470>> raised: ValueError("invalid literal for int() with base 10: 'tcp://clamav:3310'",)
2/8/2017 11:26:01 AMTraceback (most recent call last):
2/8/2017 11:26:01 AM  File "/usr/local/lib/python3.5/site-packages/celery/utils/dispatch/signal.py", line 227, in send
2/8/2017 11:26:01 AM    response = receiver(signal=self, sender=sender, **named)
2/8/2017 11:26:01 AM  File "/usr/local/lib/python3.5/site-packages/celery/fixups/django.py", line 201, in on_worker_ready
2/8/2017 11:26:01 AM    if self._settings.DEBUG:
2/8/2017 11:26:01 AM  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
2/8/2017 11:26:01 AM    self._setup(name)
2/8/2017 11:26:01 AM  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
2/8/2017 11:26:01 AM    self._wrapped = Settings(settings_module)
2/8/2017 11:26:01 AM  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
2/8/2017 11:26:01 AM    mod = importlib.import_module(self.SETTINGS_MODULE)
2/8/2017 11:26:01 AM  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
2/8/2017 11:26:01 AM    return _bootstrap._gcd_import(name[level:], package, level)
2/8/2017 11:26:01 AM  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
2/8/2017 11:26:01 AM  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
2/8/2017 11:26:01 AM  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
2/8/2017 11:26:01 AM  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
2/8/2017 11:26:01 AM  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
2/8/2017 11:26:01 AM  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2/8/2017 11:26:01 AM  File "/app/config/settings/production.py", line 8, in <module>
2/8/2017 11:26:01 AM    from .common import *  # noqa
2/8/2017 11:26:01 AM  File "/app/config/settings/common.py", line 250, in <module>
2/8/2017 11:26:01 AM    CLAMAV_PORT = env.int('CLAMAV_PORT', default=3310)
2/8/2017 11:26:01 AM  File "/usr/local/lib/python3.5/site-packages/environ/environ.py", line 152, in int
2/8/2017 11:26:01 AM    return self.get_value(var, cast=int, default=default)
2/8/2017 11:26:01 AM  File "/usr/local/lib/python3.5/site-packages/environ/environ.py", line 278, in get_value
2/8/2017 11:26:01 AM    value = self.parse_value(value, cast)
2/8/2017 11:26:01 AM  File "/usr/local/lib/python3.5/site-packages/environ/environ.py", line 334, in parse_value
2/8/2017 11:26:01 AM    value = cast(value)
2/8/2017 11:26:01 AMValueError: invalid literal for int() with base 10: 'tcp://clamav:3310'
```

**Comment by gustavofonseca** [comment]
Variáveis de ambiente de "tempo de execução" são definidas em contêineres que declaram _link_ com outros. Exemplo:

```
docker run -name first -p 5432 -d <container hash>
docker run -name second -link first:db <hash> ➊
```

No contêiner ➊ serão definidas as variáveis de ambiente referentes ao _link_ denominado _db_:
```
DB_NAME=first
DB_PORT_5432_TCP_PORT=5432
DB_PORT=tcp://172.17.0.33:5432
DB_PORT_5432_TCP=tcp://172.17.0.33:5432
DB_PORT_5432_TCP_ADDR=172.17.0.33
DB_PORT_5432_TCP_PROTO=tcp
```

**Comment by gustavofonseca** [comment]
A sugestão é de prefixar as variáveis de ambiente, ao menos as que configuram a integração com outros serviços, com ``INBOX_``.
