### ISSUE TITLE
Bug para levantar os containers Celeryworker e Celerybeat no Rancher

### ISSUE THREAD

**Issue by brunousml** [scieloorg/inbox#45]
Encontramos problemas durante o processo de deploy para o ambiente de produção. 

Os contêineres Celeryworker e Celerybeat estão encontrando problemas com Clamav. Segue abaixo o log do server. 

```bash
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/celery/worker/__init__.py", line 95, in __init__
12/21/2016 12:42:43 PM    self.app.loader.init_worker()
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/celery/loaders/base.py", line 128, in init_worker
12/21/2016 12:42:43 PM    self.import_default_modules()
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/celery/loaders/base.py", line 116, in import_default_modules
12/21/2016 12:42:43 PM    signals.import_modules.send(sender=self.app)
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/celery/utils/dispatch/signal.py", line 166, in send
12/21/2016 12:42:43 PM    response = receiver(signal=self, sender=sender, **named)
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/celery/fixups/django.py", line 73, in on_import_modules
12/21/2016 12:42:43 PM    self.worker_fixup.validate_models()
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/celery/fixups/django.py", line 158, in validate_models
12/21/2016 12:42:43 PM    django_setup()
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
12/21/2016 12:42:43 PM    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
12/21/2016 12:42:43 PM    self._setup(name)
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
12/21/2016 12:42:43 PM    self._wrapped = Settings(settings_module)
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
12/21/2016 12:42:43 PM    mod = importlib.import_module(self.SETTINGS_MODULE)
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
12/21/2016 12:42:43 PM    return _bootstrap._gcd_import(name[level:], package, level)
12/21/2016 12:42:43 PM  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
12/21/2016 12:42:43 PM  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
12/21/2016 12:42:43 PM  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
12/21/2016 12:42:43 PM  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
12/21/2016 12:42:43 PM  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
12/21/2016 12:42:43 PM  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
12/21/2016 12:42:43 PM  File "/app/config/settings/production.py", line 17, in <module>
12/21/2016 12:42:43 PM    from .common import *  # noqa
12/21/2016 12:42:43 PM  File "/app/config/settings/common.py", line 252, in <module>
12/21/2016 12:42:43 PM    CLAMAV_PORT = env.int('CLAMAV_PORT', default=3310)
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/environ/environ.py", line 137, in int
12/21/2016 12:42:43 PM    return self.get_value(var, cast=int, default=default)
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/environ/environ.py", line 263, in get_value
12/21/2016 12:42:43 PM    value = self.parse_value(value, cast)
12/21/2016 12:42:43 PM  File "/usr/local/lib/python3.5/site-packages/environ/environ.py", line 319, in parse_value
12/21/2016 12:42:43 PM    value = cast(value)
12/21/2016 12:42:43 PMValueError: invalid literal for int() with base 10: 'tcp://clamav:3310'
12/21/2016 12:42:45 PMPostgres is up - continuing...
12/21/2016 12:42:49 PMTraceback (most recent call last):
12/21/2016 12:42:49 PM  File "/usr/local/bin/celery", line 11, in <module>
12/21/2016 12:42:49 PM    sys.exit(main())
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/__main__.py", line 30, in main
12/21/2016 12:42:49 PM    main()
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 81, in main
12/21/2016 12:42:49 PM    cmd.execute_from_commandline(argv)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
12/21/2016 12:42:49 PM    super(CeleryCommand, self).execute_from_commandline(argv)))
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
12/21/2016 12:42:49 PM    return self.handle_argv(self.prog_name, argv[1:])
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 785, in handle_argv
12/21/2016 12:42:49 PM    return self.execute(command, argv)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 717, in execute
12/21/2016 12:42:49 PM    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/bin/worker.py", line 179, in run_from_argv
12/21/2016 12:42:49 PM    return self(*args, **options)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 274, in __call__
12/21/2016 12:42:49 PM    ret = self.run(*args, **kwargs)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/bin/worker.py", line 212, in run
12/21/2016 12:42:49 PM    state_db=self.node_format(state_db, hostname), **kwargs
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/worker/__init__.py", line 95, in __init__
12/21/2016 12:42:49 PM    self.app.loader.init_worker()
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/loaders/base.py", line 128, in init_worker
12/21/2016 12:42:49 PM    self.import_default_modules()
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/loaders/base.py", line 116, in import_default_modules
12/21/2016 12:42:49 PM    signals.import_modules.send(sender=self.app)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/utils/dispatch/signal.py", line 166, in send
12/21/2016 12:42:49 PM    response = receiver(signal=self, sender=sender, **named)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/fixups/django.py", line 73, in on_import_modules
12/21/2016 12:42:49 PM    self.worker_fixup.validate_models()
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/celery/fixups/django.py", line 158, in validate_models
12/21/2016 12:42:49 PM    django_setup()
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
12/21/2016 12:42:49 PM    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
12/21/2016 12:42:49 PM    self._setup(name)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
12/21/2016 12:42:49 PM    self._wrapped = Settings(settings_module)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
12/21/2016 12:42:49 PM    mod = importlib.import_module(self.SETTINGS_MODULE)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
12/21/2016 12:42:49 PM    return _bootstrap._gcd_import(name[level:], package, level)
12/21/2016 12:42:49 PM  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
12/21/2016 12:42:49 PM  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
12/21/2016 12:42:49 PM  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
12/21/2016 12:42:49 PM  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
12/21/2016 12:42:49 PM  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
12/21/2016 12:42:49 PM  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
12/21/2016 12:42:49 PM  File "/app/config/settings/production.py", line 17, in <module>
12/21/2016 12:42:49 PM    from .common import *  # noqa
12/21/2016 12:42:49 PM  File "/app/config/settings/common.py", line 252, in <module>
12/21/2016 12:42:49 PM    CLAMAV_PORT = env.int('CLAMAV_PORT', default=3310)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/environ/environ.py", line 137, in int
12/21/2016 12:42:49 PM    return self.get_value(var, cast=int, default=default)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/environ/environ.py", line 263, in get_value
12/21/2016 12:42:49 PM    value = self.parse_value(value, cast)
12/21/2016 12:42:49 PM  File "/usr/local/lib/python3.5/site-packages/environ/environ.py", line 319, in parse_value
12/21/2016 12:42:49 PM    value = cast(value)
12/21/2016 12:42:49 PMValueError: invalid literal for int() with base 10: 'tcp://clamav:3310'
```

**Comment by brunousml** [comment]
Resolvido no commit e6055ab8ed2b5a6d6911c0418690bd8dc62df9d7
