### ISSUE TITLE
Exceção *django.template.base.VariableDoesNotExist* é levantada durante a execução dos testes.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/inbox#59]
Veja https://travis-ci.org/scieloorg/inbox/builds/190308087#L674

```
DEBUG 2017-01-09 14:35:21,992 base 1 140019245217536 Exception while resolving variable 'status' in template 'unknown'.

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 885, in _resolve_lookup

    current = current[bit]

  File "/usr/local/lib/python3.5/site-packages/django/template/context.py", line 75, in __getitem__

    raise KeyError(key)

KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 891, in _resolve_lookup

    if isinstance(current, BaseContext) and getattr(type(current), bit):

AttributeError: type object 'Context' has no attribute 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 900, in _resolve_lookup

    current = current[int(bit)]

ValueError: invalid literal for int() with base 10: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 907, in _resolve_lookup

    (bit, current))  # missing attribute

django.template.base.VariableDoesNotExist: Failed lookup for key [status] in "[{'False': False, 'None': None, 'True': True}, {}]"
```

**Comment by gustavofonseca** [comment]
Essa exceção é noticiada por meio de mensagens de log do nível _DEBUG_, e não causa qualquer falha na execução dos testes. Com a integração do pull-request #92 a mensagem deixa de ser noticiada, pois o nível de log definido para a execução dos testes automatizados é o padrão do Django e a app não é executada em modo de depuração por questões de desempenho.
